[package]
name = "wasm-opt-sys"
version = "0.121.0"
description = "Native wasm-opt build"
license = "MIT / Apache-2.0"
edition = "2018"
documentation = "https://docs.rs/wasm-opt-sys"
repository = "https://github.com/brson/wasm-opt-rs"
readme = "README.md"
links = "binaryen"

[build-dependencies]
anyhow = "1.0.95"
cc = { version = "1.2.13", features = ["parallel"] }
cxx-build = "1.0.140"

[dependencies]
cxx = "1.0.140"

[features]
default = ["dwarf"]
dwarf = []
